# Generated by Django 6.0.3 on 2026-03-09 19:30

import uuid

import django.db.models.deletion
from django.db import migrations, models

STATE_CHOICES = [
    ("open", "Open"),
    ("in_review", "In Review"),
    ("accepted", "Accepted"),
    ("dropped", "Dropped"),
    ("rejected", "Rejected"),
]

VISIBILITY_CHOICES = [
    ("private", "Private"),
    ("collaborating", "Collaborating"),
]

AGENT_MODE_CHOICES = [
    ("interactive", "Interactive"),
    ("silent", "Silent"),
]

PROJECT_TYPE_CHOICES = [
    ("software", "Software"),
    ("non_software", "Non-Software"),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_id", models.UUIDField()),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")],
                        max_length=10,
                    ),
                ),
                ("sender_id", models.UUIDField(blank=True, null=True)),
                (
                    "ai_agent",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(default="regular", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_messages",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="", max_length=500)),
                (
                    "title_manually_edited",
                    models.BooleanField(default=False),
                ),
                (
                    "state",
                    models.CharField(
                        choices=STATE_CHOICES,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=VISIBILITY_CHOICES,
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "agent_mode",
                    models.CharField(
                        choices=AGENT_MODE_CHOICES,
                        default="interactive",
                        max_length=20,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=PROJECT_TYPE_CHOICES,
                        default="software",
                        max_length=20,
                    ),
                ),
                ("owner_id", models.UUIDField()),
                (
                    "share_link_token",
                    models.CharField(
                        blank=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="ProjectCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="gateway_projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_collaborators",
                "unique_together": {("project", "user_id")},
            },
        ),
    ]
