# Generated by Django 6.0.3 on 2026-03-09 22:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idea_id', models.UUIDField()),
                (
                    'node_type',
                    models.CharField(
                        choices=[('box', 'Box'), ('group', 'Group'), ('free_text', 'Free Text')],
                        max_length=15,
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_by', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('ai_modified_indicator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='board.boardnode',
                    ),
                ),
            ],
            options={
                'db_table': 'board_nodes',
            },
        ),
    ]
