"""Tests for the Facilitator agent (US-002, US-005, US-006, US-007).

Test IDs: T-2.1.03, T-2.1.04, T-2.3.01, T-2.3.02, T-2.4.01, T-2.7.01, T-2.7.02, T-2.15.01

These tests validate the FacilitatorPlugin tools, prompt rendering, and
FacilitatorAgent mock mode — all without hitting Azure OpenAI.
"""

from __future__ import annotations

import uuid

import pytest

from agents.facilitator.agent import FacilitatorAgent
from agents.facilitator.plugins import FacilitatorPlugin
from agents.facilitator.prompt import build_system_prompt
from events.publishers import clear_published_events, get_published_events


@pytest.fixture(autouse=True)
def _clear_events():
    """Clear published events before each test."""
    clear_published_events()
    yield
    clear_published_events()


def _make_user_message(msg_id: str | None = None, content: str = "Hello", sender_name: str = "Lisa") -> dict:
    return {
        "id": msg_id or str(uuid.uuid4()),
        "content": content,
        "sender_type": "user",
        "sender_name": sender_name,
        "has_ai_reaction": False,
    }


def _make_ai_message(msg_id: str | None = None, content: str = "Sure!") -> dict:
    return {
        "id": msg_id or str(uuid.uuid4()),
        "content": content,
        "sender_type": "ai",
        "sender_name": "facilitator",
        "has_ai_reaction": False,
    }


# ── T-2.1.03: Silent mode no response without @ai ──


class TestSilentModePrompt:
    """T-2.1.03: In silent mode without @ai, prompt instructs no action."""

    def test_silent_mode_no_ai_mention(self):
        prompt = build_system_prompt({
            "agent_mode": "silent",
            "project_title": "Test",
            "project_state": "open",
            "title_manually_edited": False,
            "recent_messages_formatted": '<message id="1" sender="Lisa" type="user">Hello</message>',

        })
        assert "SILENT MODE RULES" in prompt
        assert "take NO action" in prompt

    # T-2.1.04: Silent mode with @ai forces response
    def test_silent_mode_with_ai_mention(self):
        prompt = build_system_prompt({
            "agent_mode": "silent",
            "project_title": "Test",
            "project_state": "open",
            "title_manually_edited": False,
            "recent_messages_formatted": '<message id="1" sender="Lisa" type="user">@ai what do you think?</message>',

        })
        assert "SILENT MODE RULES" in prompt
        assert "you MUST respond" in prompt


# ── T-2.3.01 / T-2.3.02: Title management ──


class TestUpdateTitle:
    @pytest.mark.asyncio
    async def test_update_title_publishes_event(self):
        """T-2.3.01: update_title publishes ai.title.updated."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        result = await plugin.update_title(title="Automate Invoice Approval")
        assert result["success"] is True
        assert result["title"] == "Automate Invoice Approval"

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.title.updated"
        assert events[0]["title"] == "Automate Invoice Approval"

    @pytest.mark.asyncio
    async def test_update_title_truncates_long_title(self):
        """Title > 60 chars gets truncated."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        long_title = "A" * 80
        result = await plugin.update_title(title=long_title)
        assert len(result["title"]) == 60

    @pytest.mark.asyncio
    async def test_update_title_rejected_when_manually_edited(self):
        """T-2.3.02: update_title returns error when title_manually_edited=true."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": True},
        )
        result = await plugin.update_title(title="New Title")
        assert "error" in result
        assert result["error"]["code"] == "title_locked"
        assert len(get_published_events()) == 0


# ── US-007: update_title comprehensive AC verification ──


class TestUpdateTitleUS007:
    """US-007: update_title tool acceptance criteria."""

    @pytest.mark.asyncio
    async def test_update_title_publishes_full_event_payload(self):
        """AC-1: Publishes ai.title.updated with project_id and title."""
        plugin = FacilitatorPlugin(
            project_id="project-99",
            project_context={"title_manually_edited": False},
        )
        await plugin.update_title(title="Invoice Automation")

        events = get_published_events()
        assert len(events) == 1
        evt = events[0]
        assert evt["event_type"] == "ai.title.updated"
        assert evt["project_id"] == "project-99"
        assert evt["title"] == "Invoice Automation"
        assert "event_id" in evt  # auto-generated by publisher

    @pytest.mark.asyncio
    async def test_update_title_truncates_to_60_chars(self):
        """AC-1/AC-3: Title > 60 chars is truncated before event and in return."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        long_title = "A" * 80
        result = await plugin.update_title(title=long_title)

        # Return value truncated
        assert len(result["title"]) == 60
        assert result["title"] == "A" * 60

        # Event payload also truncated
        events = get_published_events()
        assert len(events[0]["title"]) == 60

    @pytest.mark.asyncio
    async def test_update_title_exactly_60_chars_not_truncated(self):
        """AC-3: Title exactly 60 chars passes through unchanged."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        title_60 = "B" * 60
        result = await plugin.update_title(title=title_60)
        assert result["title"] == title_60
        assert len(get_published_events()) == 1

    @pytest.mark.asyncio
    async def test_update_title_manually_edited_true_error(self):
        """AC-2: title_manually_edited=true returns title_locked error."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": True},
        )
        result = await plugin.update_title(title="New Title")
        assert "error" in result
        assert result["error"]["code"] == "title_locked"
        assert "manually edited" in result["error"]["message"]
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_update_title_manually_edited_false_succeeds(self):
        """AC-2: title_manually_edited=false allows update."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        result = await plugin.update_title(title="Allowed Title")
        assert result["success"] is True
        assert result["title"] == "Allowed Title"
        assert len(get_published_events()) == 1

    @pytest.mark.asyncio
    async def test_update_title_returns_success_and_title(self):
        """AC-4: Returns success: true and the (possibly truncated) title."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": False},
        )
        result = await plugin.update_title(title="Short Title")
        assert result == {"success": True, "title": "Short Title"}

    @pytest.mark.asyncio
    async def test_update_title_no_events_on_error(self):
        """No event published when title_manually_edited=true."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"title_manually_edited": True},
        )
        await plugin.update_title(title="Should Not Publish")
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_update_title_missing_flag_defaults_falsy(self):
        """When title_manually_edited is absent from context, update succeeds."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={},
        )
        result = await plugin.update_title(title="Works Without Flag")
        assert result["success"] is True
        assert len(get_published_events()) == 1


# ── T-2.4.01: AI can decide no action (react instead of respond) ──


class TestReactToMessage:
    @pytest.mark.asyncio
    async def test_react_to_user_message(self):
        """T-2.4.01 / T-2.7.01: react_to_message publishes ai.reaction.ready."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id, content="ok")],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_up")
        assert result["success"] is True

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.reaction.ready"
        assert events[0]["reaction_type"] == "thumbs_up"
        assert events[0]["message_id"] == msg_id

    @pytest.mark.asyncio
    async def test_react_to_ai_message_rejected(self):
        """Cannot react to AI messages."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_ai_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_up")
        assert "error" in result
        assert result["error"]["code"] == "invalid_message"

    @pytest.mark.asyncio
    async def test_react_invalid_reaction_type(self):
        """Invalid reaction_type is rejected."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="invalid")
        assert "error" in result
        assert result["error"]["code"] == "validation_error"

    @pytest.mark.asyncio
    async def test_react_duplicate_rejected(self):
        """Already reacted message returns error."""
        msg_id = str(uuid.uuid4())
        msg = _make_user_message(msg_id=msg_id)
        msg["has_ai_reaction"] = True
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"recent_messages": [msg]},
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="heart")
        assert "error" in result
        assert result["error"]["code"] == "already_reacted"


# ── US-006: react_to_message comprehensive AC verification ──


class TestReactToMessageUS006:
    """US-006: react_to_message tool acceptance criteria."""

    @pytest.mark.asyncio
    async def test_react_publishes_full_event_payload(self):
        """AC-1: Publishes ai.reaction.ready with project_id, message_id, reaction_type."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-42",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        await plugin.react_to_message(message_id=msg_id, reaction_type="heart")

        events = get_published_events()
        assert len(events) == 1
        evt = events[0]
        assert evt["event_type"] == "ai.reaction.ready"
        assert evt["project_id"] == "project-42"
        assert evt["message_id"] == msg_id
        assert evt["reaction_type"] == "heart"
        assert "event_id" in evt  # auto-generated by publisher

    @pytest.mark.asyncio
    async def test_react_thumbs_down(self):
        """AC-1: thumbs_down reaction type publishes correctly."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_down")
        assert result["success"] is True
        events = get_published_events()
        assert events[0]["reaction_type"] == "thumbs_down"

    @pytest.mark.asyncio
    async def test_react_thumbs_up(self):
        """AC-1: thumbs_up reaction type publishes correctly."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_up")
        assert result["success"] is True
        events = get_published_events()
        assert events[0]["reaction_type"] == "thumbs_up"

    @pytest.mark.asyncio
    async def test_react_to_ai_message_error(self):
        """AC-2: Reacting to AI message returns error."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_ai_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_up")
        assert "error" in result
        assert result["error"]["code"] == "invalid_message"
        assert "AI messages" in result["error"]["message"]
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_react_duplicate_error(self):
        """AC-2 / T-2.7.02: Duplicate reaction (UNIQUE constraint) returns error."""
        msg_id = str(uuid.uuid4())
        msg = _make_user_message(msg_id=msg_id)
        msg["has_ai_reaction"] = True
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"recent_messages": [msg]},
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="thumbs_up")
        assert "error" in result
        assert result["error"]["code"] == "already_reacted"
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_react_message_not_found_error(self):
        """AC-2: Nonexistent message_id returns error."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message()],
            },
        )
        result = await plugin.react_to_message(
            message_id="nonexistent-id", reaction_type="heart"
        )
        assert "error" in result
        assert result["error"]["code"] == "invalid_message"
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_react_returns_success_true(self):
        """AC-3: Returns success: true on valid reaction."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="heart")
        assert result == {"success": True}

    @pytest.mark.asyncio
    async def test_react_no_events_on_error(self):
        """No event published when validation fails (invalid type)."""
        msg_id = str(uuid.uuid4())
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={
                "recent_messages": [_make_user_message(msg_id=msg_id)],
            },
        )
        result = await plugin.react_to_message(message_id=msg_id, reaction_type="angry")
        assert "error" in result
        assert len(get_published_events()) == 0


# ── send_chat_message ──


class TestSendChatMessage:
    """US-005: send_chat_message tool acceptance criteria."""

    @pytest.mark.asyncio
    async def test_send_chat_message_publishes_event(self):
        """AC-1: Publishes ai.chat_response.ready with full payload."""
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.send_chat_message(content="Hello user!", message_type="regular")
        assert result["message_id"] is None  # placeholder — Gateway fills
        assert result["created_at"] is None  # placeholder — Gateway fills

        events = get_published_events()
        assert len(events) == 1
        evt = events[0]
        assert evt["event_type"] == "ai.chat_response.ready"
        assert evt["project_id"] == "project-1"
        assert evt["content"] == "Hello user!"
        assert evt["sender_type"] == "ai"
        assert evt["ai_agent"] == "facilitator"
        assert evt["message_type"] == "regular"
        assert "event_id" in evt  # auto-generated by publisher

    @pytest.mark.asyncio
    async def test_send_delegation_message_type(self):
        """AC-1: delegation message_type is preserved in event."""
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.send_chat_message(content="Delegated result", message_type="delegation")
        assert result["message_id"] is None

        events = get_published_events()
        assert events[0]["message_type"] == "delegation"

    @pytest.mark.asyncio
    async def test_send_invalid_message_type_defaults_regular(self):
        """Invalid message_type silently defaults to regular."""
        plugin = FacilitatorPlugin(project_id="project-1")
        await plugin.send_chat_message(content="Hi", message_type="bogus")
        events = get_published_events()
        assert events[0]["message_type"] == "regular"

    @pytest.mark.asyncio
    async def test_send_empty_content_rejected(self):
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.send_chat_message(content="", message_type="regular")
        assert "error" in result
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_send_whitespace_only_rejected(self):
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.send_chat_message(content="   ", message_type="regular")
        assert "error" in result
        assert len(get_published_events()) == 0



# ── T-2.15.01: Facilitator delegates ──


class TestDelegation:
    @pytest.mark.asyncio
    async def test_delegate_to_context_agent(self):
        """T-2.15.01: delegate_to_context_agent publishes ai.delegation.started."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_context_bucket_has_content", return_value=True):
            result = await plugin.delegate_to_context_agent(
                query="What document management system does Commerz Real use?"
            )
        assert result["status"] == "queued"
        assert "delegation_id" in result

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.delegation.started"
        assert events[0]["delegation_type"] == "context_agent"
        assert plugin.delegations[0]["delegation_type"] == "context_agent"

    @pytest.mark.asyncio
    async def test_delegate_to_context_extension(self):
        """delegate_to_context_extension publishes ai.delegation.started."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_has_compressed_context", return_value=True):
            result = await plugin.delegate_to_context_extension(
                query="What did Lisa say about digital signatures?"
            )
        assert result["status"] == "queued"
        assert "delegation_id" in result

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.delegation.started"
        assert events[0]["delegation_type"] == "context_extension"

    @pytest.mark.asyncio
    async def test_delegation_empty_query_rejected(self):
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.delegate_to_context_agent(query="")
        assert "error" in result

    @pytest.mark.asyncio
    async def test_delegation_empty_bucket_rejected(self):
        """T-2.15.02: delegate_to_context_agent returns error when bucket is empty."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_context_bucket_has_content", return_value=False):
            result = await plugin.delegate_to_context_agent(
                query="What system does the company use?"
            )
        assert "error" in result
        assert result["error"]["code"] == "no_context_available"
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_delegate_to_context_extension_empty_query_rejected(self):
        """delegate_to_context_extension with empty query returns error."""
        plugin = FacilitatorPlugin(project_id="project-1")
        result = await plugin.delegate_to_context_extension(query="")
        assert "error" in result
        assert result["error"]["code"] == "validation_error"

    @pytest.mark.asyncio
    async def test_delegate_to_context_extension_no_compressed_context_rejected(self):
        """delegate_to_context_extension returns error when no compression exists."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_has_compressed_context", return_value=False):
            result = await plugin.delegate_to_context_extension(
                query="What did Lisa say about digital signatures?"
            )
        assert "error" in result
        assert result["error"]["code"] == "no_compressed_context"
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_delegate_to_context_extension_with_compressed_context_succeeds(self):
        """delegate_to_context_extension succeeds when compression exists."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_has_compressed_context", return_value=True):
            result = await plugin.delegate_to_context_extension(
                query="What did Lisa say about digital signatures?"
            )
        assert result["status"] == "queued"
        assert "delegation_id" in result
        assert plugin.delegations[0]["delegation_type"] == "context_extension"

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.delegation.started"
        assert events[0]["delegation_type"] == "context_extension"

    @pytest.mark.asyncio
    async def test_delegation_with_bucket_content_succeeds(self):
        """delegate_to_context_agent succeeds when bucket has content."""
        from unittest.mock import patch

        plugin = FacilitatorPlugin(project_id="project-1")
        with patch.object(plugin, "_context_bucket_has_content", return_value=True):
            result = await plugin.delegate_to_context_agent(
                query="What document management system is used?"
            )
        assert result["status"] == "queued"
        assert "delegation_id" in result
        assert plugin.delegations[0]["delegation_type"] == "context_agent"

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.delegation.started"



# ── FacilitatorAgent mock mode ──


class TestFacilitatorAgentMockMode:
    @pytest.mark.asyncio
    async def test_mock_mode_returns_fixture(self, settings):
        """FacilitatorAgent.process() in mock mode returns fixture data."""
        from pathlib import Path

        settings.AI_MOCK_MODE = True
        # BASE_DIR in tests points to gateway; override to AI service root
        settings.BASE_DIR = Path(__file__).resolve().parent.parent
        agent = FacilitatorAgent()
        result = await agent.process({"project_id": "test-project"})
        assert "response" in result
        assert result["delegations"] == []


# ── System prompt rendering ──


class TestSystemPromptRendering:
    def test_interactive_mode_prompt(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Invoice Automation",
            "project_state": "open",
            "title_manually_edited": False,
            "facilitator_bucket_content": "Systems: SAP, DocuSign",
            "recent_messages_formatted": "(no messages yet)",

            "no_messages_yet": True,
            "creator_language": "German",
        })
        assert "INTERACTIVE MODE RULES" in prompt
        assert "Invoice Automation" in prompt
        assert "SAP, DocuSign" in prompt
        assert "German" in prompt
        assert "SILENT MODE RULES" not in prompt

    def test_prompt_with_compressed_summary(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "title_manually_edited": False,
            "chat_summary": "Previous discussion about workflows.",
            "recent_messages_formatted": "",

        })
        assert "<compressed_summary>" in prompt
        assert "Previous discussion about workflows." in prompt
        assert "context extension agent" in prompt

    def test_prompt_with_delegation_results(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "title_manually_edited": False,
            "delegation_results": "Commerz Real uses SAP for ERP.",
            "recent_messages_formatted": "",

        })
        assert "<delegation_results>" in prompt
        assert "Commerz Real uses SAP for ERP." in prompt

    def test_prompt_multi_user(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "title_manually_edited": False,
            "is_multi_user": True,
            "user_names_list": "Lisa, Max",
            "recent_messages_formatted": "",

        })
        assert "Lisa, Max" in prompt
        assert "Multiple users" in prompt

    def test_prompt_includes_project_type(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "<project_type>software</project_type>" in prompt

    def test_prompt_includes_requirements_structure_software(self):
        structure = [
            {
                "id": "epic-1",
                "type": "epic",
                "title": "User Auth",
                "children": [
                    {"id": "story-1", "type": "user_story", "title": "Login", "priority": "High"},
                ],
            }
        ]
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
            "requirements_structure": structure,
        })
        assert "Epics and User Stories:" in prompt
        assert "Epic epic-1: User Auth" in prompt
        assert "Story story-1: Login" in prompt
        assert "Priority: High" in prompt

    def test_prompt_includes_requirements_structure_non_software(self):
        structure = [
            {
                "id": "ms-1",
                "type": "milestone",
                "title": "Phase 1",
                "children": [
                    {"id": "wp-1", "type": "work_package", "title": "Deliverable A"},
                ],
            }
        ]
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "non_software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
            "requirements_structure": structure,
        })
        assert "Milestones and Work Packages:" in prompt
        assert "Milestone ms-1: Phase 1" in prompt
        assert "Package wp-1: Deliverable A" in prompt
        assert "<project_type>non_software</project_type>" in prompt

    def test_prompt_empty_requirements_structure(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "No requirements structure yet" in prompt

    def test_prompt_software_structuring_guidance(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "SOFTWARE PROJECT GUIDANCE" in prompt
        assert "Epic" in prompt

    def test_prompt_non_software_structuring_guidance(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "non_software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "NON-SOFTWARE PROJECT GUIDANCE" in prompt
        assert "Milestone" in prompt

    def test_prompt_no_board_references(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "board" not in prompt.lower()
        assert "[[" not in prompt

    def test_prompt_identity_mentions_requirements_assembly(self):
        prompt = build_system_prompt({
            "agent_mode": "interactive",
            "project_title": "Test",
            "project_state": "open",
            "project_type": "software",
            "title_manually_edited": False,
            "recent_messages_formatted": "",
        })
        assert "requirements assembly platform" in prompt
        assert "Requirements Assistant" in prompt


# ── US-001 (M20): update_requirements_structure tool ──


class TestUpdateRequirementsStructure:
    """Tests for the update_requirements_structure Facilitator tool."""

    @pytest.mark.asyncio
    async def test_add_epic_software_project(self):
        """add_epic succeeds for software projects."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([{"operation": "add_epic", "data": {"title": "User Auth"}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is True
        assert result["mutation_count"] == 1
        assert result["mutations_applied"][0]["status"] == "success"
        assert len(plugin.requirements_mutations) == 1

        events = get_published_events()
        assert len(events) == 1
        assert events[0]["event_type"] == "ai.requirements.updated"
        assert events[0]["operation"] == "add_epic"

    @pytest.mark.asyncio
    async def test_add_epic_rejected_for_non_software(self):
        """add_epic fails for non_software projects."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "non_software"},
        )
        mutations = json.dumps([{"operation": "add_epic", "data": {"title": "Epic"}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is False
        assert result["mutation_count"] == 0
        assert result["mutations_applied"][0]["status"] == "failed"
        assert "not valid for non_software" in result["mutations_applied"][0]["error"]
        assert len(get_published_events()) == 0

    @pytest.mark.asyncio
    async def test_add_milestone_non_software_project(self):
        """add_milestone succeeds for non_software projects."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "non_software"},
        )
        mutations = json.dumps([{"operation": "add_milestone", "data": {"title": "Phase 1"}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is True
        assert result["mutation_count"] == 1
        assert result["mutations_applied"][0]["status"] == "success"

    @pytest.mark.asyncio
    async def test_add_milestone_rejected_for_software(self):
        """add_milestone fails for software projects."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([{"operation": "add_milestone", "data": {"title": "Phase 1"}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is False
        assert result["mutations_applied"][0]["status"] == "failed"

    @pytest.mark.asyncio
    async def test_unknown_operation_rejected(self):
        """Unknown operation name returns failed."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([{"operation": "delete_all", "data": {}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is False
        assert "Unknown operation" in result["mutations_applied"][0]["error"]

    @pytest.mark.asyncio
    async def test_missing_required_fields(self):
        """Missing required fields returns validation error."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([{"operation": "add_story", "data": {"title": "Story"}}])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is False
        assert "epic_id" in result["mutations_applied"][0]["error"]

    @pytest.mark.asyncio
    async def test_invalid_json_mutations(self):
        """Invalid JSON returns validation error."""
        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        result = await plugin.update_requirements_structure(mutations="not json")
        assert "error" in result
        assert result["error"]["code"] == "validation_error"

    @pytest.mark.asyncio
    async def test_empty_mutations_array(self):
        """Empty mutations array returns validation error."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        result = await plugin.update_requirements_structure(mutations=json.dumps([]))
        assert "error" in result
        assert result["error"]["code"] == "validation_error"

    @pytest.mark.asyncio
    async def test_multiple_mutations_mixed_results(self):
        """Multiple mutations with partial success."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([
            {"operation": "add_epic", "data": {"title": "Epic 1"}},
            {"operation": "add_milestone", "data": {"title": "Phase 1"}},  # wrong type
            {"operation": "add_epic", "data": {"title": "Epic 2"}},
        ])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is True
        assert result["mutation_count"] == 2
        assert result["mutations_applied"][0]["status"] == "success"
        assert result["mutations_applied"][1]["status"] == "failed"
        assert result["mutations_applied"][2]["status"] == "success"
        assert len(plugin.requirements_mutations) == 2

        events = get_published_events()
        assert len(events) == 2
        assert all(e["event_type"] == "ai.requirements.updated" for e in events)

    @pytest.mark.asyncio
    async def test_add_story_with_all_fields(self):
        """add_story with complete data succeeds."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "software"},
        )
        mutations = json.dumps([{
            "operation": "add_story",
            "data": {
                "epic_id": "epic-1",
                "title": "As a user, I want to log in so that I can access the system",
                "description": "Login story",
                "acceptance_criteria": "- Can enter credentials\n- Gets error on invalid",
                "priority": "High",
            },
        }])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is True
        assert result["mutation_count"] == 1

    @pytest.mark.asyncio
    async def test_add_package_with_all_fields(self):
        """add_package with complete data succeeds for non_software."""
        import json

        plugin = FacilitatorPlugin(
            project_id="project-1",
            project_context={"project_type": "non_software"},
        )
        mutations = json.dumps([{
            "operation": "add_package",
            "data": {
                "milestone_id": "ms-1",
                "title": "Setup infrastructure",
                "description": "Deploy servers",
                "deliverables": "- Server setup\n- Network config",
                "dependencies": "Procurement approval",
            },
        }])
        result = await plugin.update_requirements_structure(mutations=mutations)
        assert result["accepted"] is True
        assert result["mutation_count"] == 1

    @pytest.mark.asyncio
    async def test_all_16_operations_valid(self):
        """All 16 operations are recognized (not unknown)."""
        import json

        all_ops = [
            "add_epic", "update_epic", "remove_epic", "reorder_epics",
            "add_story", "update_story", "remove_story", "reorder_stories",
            "add_milestone", "update_milestone", "remove_milestone", "reorder_milestones",
            "add_package", "update_package", "remove_package", "reorder_packages",
        ]
        for op in all_ops:
            plugin = FacilitatorPlugin(
                project_id="project-1",
                project_context={"project_type": "software"},
            )
            clear_published_events()
            mutations = json.dumps([{"operation": op, "data": {"title": "t", "epic_id": "e", "story_id": "s", "milestone_id": "m", "package_id": "p", "order": ["a"]}}])
            result = await plugin.update_requirements_structure(mutations=mutations)
            # Should not have "Unknown operation" error
            applied = result["mutations_applied"][0]
            assert "Unknown operation" not in (applied.get("error") or ""), f"Op {op} was unknown"
