# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerChatProcessing = channel.unary_unary(
                '/ziqreq.ai.AiService/TriggerChatProcessing',
                request_serializer=ai__pb2.ChatProcessingRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatProcessingResponse.FromString,
                _registered_method=True)
        self.TriggerBrdGeneration = channel.unary_unary(
                '/ziqreq.ai.AiService/TriggerBrdGeneration',
                request_serializer=ai__pb2.BrdGenerationRequest.SerializeToString,
                response_deserializer=ai__pb2.BrdGenerationResponse.FromString,
                _registered_method=True)
        self.TriggerContextReindex = channel.unary_unary(
                '/ziqreq.ai.AiService/TriggerContextReindex',
                request_serializer=ai__pb2.ContextReindexRequest.SerializeToString,
                response_deserializer=ai__pb2.ContextReindexResponse.FromString,
                _registered_method=True)
        self.GetFacilitatorBucket = channel.unary_unary(
                '/ziqreq.ai.AiService/GetFacilitatorBucket',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ai__pb2.FacilitatorBucketResponse.FromString,
                _registered_method=True)
        self.UpdateFacilitatorBucket = channel.unary_unary(
                '/ziqreq.ai.AiService/UpdateFacilitatorBucket',
                request_serializer=ai__pb2.UpdateFacilitatorBucketRequest.SerializeToString,
                response_deserializer=ai__pb2.FacilitatorBucketResponse.FromString,
                _registered_method=True)
        self.GetContextAgentBucket = channel.unary_unary(
                '/ziqreq.ai.AiService/GetContextAgentBucket',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ai__pb2.ContextAgentBucketResponse.FromString,
                _registered_method=True)
        self.UpdateContextAgentBucket = channel.unary_unary(
                '/ziqreq.ai.AiService/UpdateContextAgentBucket',
                request_serializer=ai__pb2.UpdateContextAgentBucketRequest.SerializeToString,
                response_deserializer=ai__pb2.ContextAgentBucketResponse.FromString,
                _registered_method=True)
        self.GetAiMetrics = channel.unary_unary(
                '/ziqreq.ai.AiService/GetAiMetrics',
                request_serializer=ai__pb2.AiMetricsRequest.SerializeToString,
                response_deserializer=ai__pb2.AiMetricsResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerChatProcessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerBrdGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerContextReindex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFacilitatorBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFacilitatorBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContextAgentBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateContextAgentBucket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAiMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerChatProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerChatProcessing,
                    request_deserializer=ai__pb2.ChatProcessingRequest.FromString,
                    response_serializer=ai__pb2.ChatProcessingResponse.SerializeToString,
            ),
            'TriggerBrdGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerBrdGeneration,
                    request_deserializer=ai__pb2.BrdGenerationRequest.FromString,
                    response_serializer=ai__pb2.BrdGenerationResponse.SerializeToString,
            ),
            'TriggerContextReindex': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerContextReindex,
                    request_deserializer=ai__pb2.ContextReindexRequest.FromString,
                    response_serializer=ai__pb2.ContextReindexResponse.SerializeToString,
            ),
            'GetFacilitatorBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacilitatorBucket,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ai__pb2.FacilitatorBucketResponse.SerializeToString,
            ),
            'UpdateFacilitatorBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFacilitatorBucket,
                    request_deserializer=ai__pb2.UpdateFacilitatorBucketRequest.FromString,
                    response_serializer=ai__pb2.FacilitatorBucketResponse.SerializeToString,
            ),
            'GetContextAgentBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContextAgentBucket,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ai__pb2.ContextAgentBucketResponse.SerializeToString,
            ),
            'UpdateContextAgentBucket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateContextAgentBucket,
                    request_deserializer=ai__pb2.UpdateContextAgentBucketRequest.FromString,
                    response_serializer=ai__pb2.ContextAgentBucketResponse.SerializeToString,
            ),
            'GetAiMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAiMetrics,
                    request_deserializer=ai__pb2.AiMetricsRequest.FromString,
                    response_serializer=ai__pb2.AiMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ziqreq.ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ziqreq.ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerChatProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/TriggerChatProcessing',
            ai__pb2.ChatProcessingRequest.SerializeToString,
            ai__pb2.ChatProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerBrdGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/TriggerBrdGeneration',
            ai__pb2.BrdGenerationRequest.SerializeToString,
            ai__pb2.BrdGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerContextReindex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/TriggerContextReindex',
            ai__pb2.ContextReindexRequest.SerializeToString,
            ai__pb2.ContextReindexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFacilitatorBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/GetFacilitatorBucket',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ai__pb2.FacilitatorBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFacilitatorBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/UpdateFacilitatorBucket',
            ai__pb2.UpdateFacilitatorBucketRequest.SerializeToString,
            ai__pb2.FacilitatorBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContextAgentBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/GetContextAgentBucket',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ai__pb2.ContextAgentBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateContextAgentBucket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/UpdateContextAgentBucket',
            ai__pb2.UpdateContextAgentBucketRequest.SerializeToString,
            ai__pb2.ContextAgentBucketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAiMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.ai.AiService/GetAiMetrics',
            ai__pb2.AiMetricsRequest.SerializeToString,
            ai__pb2.AiMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
