# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\rziqreq.common\":\n\x07UserRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"4\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"J\n\x12PaginationResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x85\x01\n\x08Reaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x15\n\rreaction_type\x18\x03 \x01(\t\x12\x17\n\x0f\x63reated_by_type\x18\x04 \x01(\t\x12\x15\n\rcreated_by_id\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"\xc3\x01\n\tBoardNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07idea_id\x18\x02 \x01(\t\x12\x11\n\tnode_type\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x12\n\nx_position\x18\x05 \x01(\x01\x12\x12\n\ny_position\x18\x06 \x01(\x01\x12\x11\n\tparent_id\x18\x07 \x01(\t\x12\x12\n\nsort_order\x18\x08 \x01(\x05\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\"\x81\x01\n\x0f\x42oardConnection\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07idea_id\x18\x02 \x01(\t\x12\x16\n\x0esource_node_id\x18\x03 \x01(\t\x12\x16\n\x0etarget_node_id\x18\x04 \x01(\t\x12\r\n\x05label\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREF']._serialized_start=31
  _globals['_USERREF']._serialized_end=89
  _globals['_PAGINATIONREQUEST']._serialized_start=91
  _globals['_PAGINATIONREQUEST']._serialized_end=143
  _globals['_PAGINATIONRESPONSE']._serialized_start=145
  _globals['_PAGINATIONRESPONSE']._serialized_end=219
  _globals['_ERROR']._serialized_start=221
  _globals['_ERROR']._serialized_end=259
  _globals['_REACTION']._serialized_start=262
  _globals['_REACTION']._serialized_end=395
  _globals['_BOARDNODE']._serialized_start=398
  _globals['_BOARDNODE']._serialized_end=593
  _globals['_BOARDCONNECTION']._serialized_start=596
  _globals['_BOARDCONNECTION']._serialized_end=725
# @@protoc_insertion_point(module_scope)
