# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProjectContext = channel.unary_unary(
                '/ziqreq.core.CoreService/GetProjectContext',
                request_serializer=core__pb2.ProjectContextRequest.SerializeToString,
                response_deserializer=core__pb2.ProjectContextResponse.FromString,
                _registered_method=True)
        self.GetFullChatHistory = channel.unary_unary(
                '/ziqreq.core.CoreService/GetFullChatHistory',
                request_serializer=core__pb2.FullChatHistoryRequest.SerializeToString,
                response_deserializer=core__pb2.FullChatHistoryResponse.FromString,
                _registered_method=True)
        self.PersistAiChatMessage = channel.unary_unary(
                '/ziqreq.core.CoreService/PersistAiChatMessage',
                request_serializer=core__pb2.AiChatMessageRequest.SerializeToString,
                response_deserializer=core__pb2.AiChatMessageResponse.FromString,
                _registered_method=True)
        self.PersistAiReaction = channel.unary_unary(
                '/ziqreq.core.CoreService/PersistAiReaction',
                request_serializer=core__pb2.AiReactionRequest.SerializeToString,
                response_deserializer=core__pb2.AiReactionResponse.FromString,
                _registered_method=True)
        self.UpdateProjectTitle = channel.unary_unary(
                '/ziqreq.core.CoreService/UpdateProjectTitle',
                request_serializer=core__pb2.UpdateTitleRequest.SerializeToString,
                response_deserializer=core__pb2.UpdateTitleResponse.FromString,
                _registered_method=True)
        self.UpdateBrdDraft = channel.unary_unary(
                '/ziqreq.core.CoreService/UpdateBrdDraft',
                request_serializer=core__pb2.UpdateBrdDraftRequest.SerializeToString,
                response_deserializer=core__pb2.UpdateBrdDraftResponse.FromString,
                _registered_method=True)
        self.GetProjectsByState = channel.unary_unary(
                '/ziqreq.core.CoreService/GetProjectsByState',
                request_serializer=core__pb2.ProjectsByStateRequest.SerializeToString,
                response_deserializer=core__pb2.ProjectsByStateResponse.FromString,
                _registered_method=True)
        self.GetUserStats = channel.unary_unary(
                '/ziqreq.core.CoreService/GetUserStats',
                request_serializer=core__pb2.GetUserStatsRequest.SerializeToString,
                response_deserializer=core__pb2.UserStatsResponse.FromString,
                _registered_method=True)
        self.GetRateLimitStatus = channel.unary_unary(
                '/ziqreq.core.CoreService/GetRateLimitStatus',
                request_serializer=core__pb2.RateLimitRequest.SerializeToString,
                response_deserializer=core__pb2.RateLimitResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProjectContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistAiChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistAiReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProjectTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBrdDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectsByState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRateLimitStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProjectContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectContext,
                    request_deserializer=core__pb2.ProjectContextRequest.FromString,
                    response_serializer=core__pb2.ProjectContextResponse.SerializeToString,
            ),
            'GetFullChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullChatHistory,
                    request_deserializer=core__pb2.FullChatHistoryRequest.FromString,
                    response_serializer=core__pb2.FullChatHistoryResponse.SerializeToString,
            ),
            'PersistAiChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistAiChatMessage,
                    request_deserializer=core__pb2.AiChatMessageRequest.FromString,
                    response_serializer=core__pb2.AiChatMessageResponse.SerializeToString,
            ),
            'PersistAiReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistAiReaction,
                    request_deserializer=core__pb2.AiReactionRequest.FromString,
                    response_serializer=core__pb2.AiReactionResponse.SerializeToString,
            ),
            'UpdateProjectTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProjectTitle,
                    request_deserializer=core__pb2.UpdateTitleRequest.FromString,
                    response_serializer=core__pb2.UpdateTitleResponse.SerializeToString,
            ),
            'UpdateBrdDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBrdDraft,
                    request_deserializer=core__pb2.UpdateBrdDraftRequest.FromString,
                    response_serializer=core__pb2.UpdateBrdDraftResponse.SerializeToString,
            ),
            'GetProjectsByState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectsByState,
                    request_deserializer=core__pb2.ProjectsByStateRequest.FromString,
                    response_serializer=core__pb2.ProjectsByStateResponse.SerializeToString,
            ),
            'GetUserStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStats,
                    request_deserializer=core__pb2.GetUserStatsRequest.FromString,
                    response_serializer=core__pb2.UserStatsResponse.SerializeToString,
            ),
            'GetRateLimitStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRateLimitStatus,
                    request_deserializer=core__pb2.RateLimitRequest.FromString,
                    response_serializer=core__pb2.RateLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ziqreq.core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ziqreq.core.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProjectContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/GetProjectContext',
            core__pb2.ProjectContextRequest.SerializeToString,
            core__pb2.ProjectContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/GetFullChatHistory',
            core__pb2.FullChatHistoryRequest.SerializeToString,
            core__pb2.FullChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistAiChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/PersistAiChatMessage',
            core__pb2.AiChatMessageRequest.SerializeToString,
            core__pb2.AiChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistAiReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/PersistAiReaction',
            core__pb2.AiReactionRequest.SerializeToString,
            core__pb2.AiReactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProjectTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/UpdateProjectTitle',
            core__pb2.UpdateTitleRequest.SerializeToString,
            core__pb2.UpdateTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBrdDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/UpdateBrdDraft',
            core__pb2.UpdateBrdDraftRequest.SerializeToString,
            core__pb2.UpdateBrdDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectsByState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/GetProjectsByState',
            core__pb2.ProjectsByStateRequest.SerializeToString,
            core__pb2.ProjectsByStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/GetUserStats',
            core__pb2.GetUserStatsRequest.SerializeToString,
            core__pb2.UserStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRateLimitStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.core.CoreService/GetRateLimitStatus',
            core__pb2.RateLimitRequest.SerializeToString,
            core__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
