# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x0eziqreq.gateway\"\x8b\x01\n\x19\x43reateNotificationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x14\n\x0creference_id\x18\x05 \x01(\t\x12\x16\n\x0ereference_type\x18\x06 \x01(\t\"5\n\x1a\x43reateNotificationResponse\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\")\n\x16UserPreferencesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x87\x02\n\x17UserPreferencesResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12q\n\x1e\x65mail_notification_preferences\x18\x04 \x03(\x0b\x32I.ziqreq.gateway.UserPreferencesResponse.EmailNotificationPreferencesEntry\x1a\x43\n!EmailNotificationPreferencesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x18\n\x16\x41lertRecipientsRequest\"M\n\x17\x41lertRecipientsResponse\x12\x32\n\nrecipients\x18\x01 \x03(\x0b\x32\x1e.ziqreq.gateway.AlertRecipient\"F\n\x0e\x41lertRecipient\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t2\xcb\x02\n\x0eGatewayService\x12k\n\x12\x43reateNotification\x12).ziqreq.gateway.CreateNotificationRequest\x1a*.ziqreq.gateway.CreateNotificationResponse\x12\x65\n\x12GetUserPreferences\x12&.ziqreq.gateway.UserPreferencesRequest\x1a\'.ziqreq.gateway.UserPreferencesResponse\x12\x65\n\x12GetAlertRecipients\x12&.ziqreq.gateway.AlertRecipientsRequest\x1a\'.ziqreq.gateway.AlertRecipientsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPREFERENCESRESPONSE_EMAILNOTIFICATIONPREFERENCESENTRY']._loaded_options = None
  _globals['_USERPREFERENCESRESPONSE_EMAILNOTIFICATIONPREFERENCESENTRY']._serialized_options = b'8\001'
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_start=34
  _globals['_CREATENOTIFICATIONREQUEST']._serialized_end=173
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_start=175
  _globals['_CREATENOTIFICATIONRESPONSE']._serialized_end=228
  _globals['_USERPREFERENCESREQUEST']._serialized_start=230
  _globals['_USERPREFERENCESREQUEST']._serialized_end=271
  _globals['_USERPREFERENCESRESPONSE']._serialized_start=274
  _globals['_USERPREFERENCESRESPONSE']._serialized_end=537
  _globals['_USERPREFERENCESRESPONSE_EMAILNOTIFICATIONPREFERENCESENTRY']._serialized_start=470
  _globals['_USERPREFERENCESRESPONSE_EMAILNOTIFICATIONPREFERENCESENTRY']._serialized_end=537
  _globals['_ALERTRECIPIENTSREQUEST']._serialized_start=539
  _globals['_ALERTRECIPIENTSREQUEST']._serialized_end=563
  _globals['_ALERTRECIPIENTSRESPONSE']._serialized_start=565
  _globals['_ALERTRECIPIENTSRESPONSE']._serialized_end=642
  _globals['_ALERTRECIPIENT']._serialized_start=644
  _globals['_ALERTRECIPIENT']._serialized_end=714
  _globals['_GATEWAYSERVICE']._serialized_start=717
  _globals['_GATEWAYSERVICE']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
