# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotification = channel.unary_unary(
                '/ziqreq.gateway.GatewayService/CreateNotification',
                request_serializer=gateway__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=gateway__pb2.CreateNotificationResponse.FromString,
                _registered_method=True)
        self.GetUserPreferences = channel.unary_unary(
                '/ziqreq.gateway.GatewayService/GetUserPreferences',
                request_serializer=gateway__pb2.UserPreferencesRequest.SerializeToString,
                response_deserializer=gateway__pb2.UserPreferencesResponse.FromString,
                _registered_method=True)
        self.GetAlertRecipients = channel.unary_unary(
                '/ziqreq.gateway.GatewayService/GetAlertRecipients',
                request_serializer=gateway__pb2.AlertRecipientsRequest.SerializeToString,
                response_deserializer=gateway__pb2.AlertRecipientsResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlertRecipients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=gateway__pb2.CreateNotificationRequest.FromString,
                    response_serializer=gateway__pb2.CreateNotificationResponse.SerializeToString,
            ),
            'GetUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPreferences,
                    request_deserializer=gateway__pb2.UserPreferencesRequest.FromString,
                    response_serializer=gateway__pb2.UserPreferencesResponse.SerializeToString,
            ),
            'GetAlertRecipients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlertRecipients,
                    request_deserializer=gateway__pb2.AlertRecipientsRequest.FromString,
                    response_serializer=gateway__pb2.AlertRecipientsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ziqreq.gateway.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ziqreq.gateway.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.gateway.GatewayService/CreateNotification',
            gateway__pb2.CreateNotificationRequest.SerializeToString,
            gateway__pb2.CreateNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.gateway.GatewayService/GetUserPreferences',
            gateway__pb2.UserPreferencesRequest.SerializeToString,
            gateway__pb2.UserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlertRecipients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ziqreq.gateway.GatewayService/GetAlertRecipients',
            gateway__pb2.AlertRecipientsRequest.SerializeToString,
            gateway__pb2.AlertRecipientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
