# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdf.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pdf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpdf.proto\x12\nziqreq.pdf\"\xc4\x01\n\x14PdfGenerationRequest\x12\x0f\n\x07idea_id\x18\x01 \x01(\t\x12\x12\n\nidea_title\x18\x02 \x01(\t\x12@\n\x08sections\x18\x03 \x03(\x0b\x32..ziqreq.pdf.PdfGenerationRequest.SectionsEntry\x12\x14\n\x0cgenerated_at\x18\x04 \x01(\t\x1a/\n\rSectionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x15PdfGenerationResponse\x12\x10\n\x08pdf_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t2`\n\nPdfService\x12R\n\x0bGeneratePdf\x12 .ziqreq.pdf.PdfGenerationRequest\x1a!.ziqreq.pdf.PdfGenerationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PDFGENERATIONREQUEST_SECTIONSENTRY']._loaded_options = None
  _globals['_PDFGENERATIONREQUEST_SECTIONSENTRY']._serialized_options = b'8\001'
  _globals['_PDFGENERATIONREQUEST']._serialized_start=26
  _globals['_PDFGENERATIONREQUEST']._serialized_end=222
  _globals['_PDFGENERATIONREQUEST_SECTIONSENTRY']._serialized_start=175
  _globals['_PDFGENERATIONREQUEST_SECTIONSENTRY']._serialized_end=222
  _globals['_PDFGENERATIONRESPONSE']._serialized_start=224
  _globals['_PDFGENERATIONRESPONSE']._serialized_end=283
  _globals['_PDFSERVICE']._serialized_start=285
  _globals['_PDFSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
